CREATE TABLE users (
 id BIGSERIAL PRIMARY KEY, first_name VARCHAR(100) NOT NULL, last_name VARCHAR(100) NOT NULL, email VARCHAR(255) NOT NULL UNIQUE, password VARCHAR(255) NOT NULL, role VARCHAR(30) NOT NULL DEFAULT 'USER', created_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP, updated_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP
);
CREATE TABLE accounts (
 id BIGSERIAL PRIMARY KEY, name VARCHAR(100) NOT NULL, account_type VARCHAR(30) NOT NULL, balance NUMERIC(19,2) NOT NULL DEFAULT 0 CHECK (balance >= 0), user_id BIGINT NOT NULL REFERENCES users(id) ON DELETE CASCADE, created_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP, updated_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP
);
CREATE INDEX idx_accounts_user ON accounts(user_id);
CREATE TABLE budgets (
 id BIGSERIAL PRIMARY KEY, category VARCHAR(80) NOT NULL, amount NUMERIC(19,2) NOT NULL CHECK (amount > 0), month DATE NOT NULL, user_id BIGINT NOT NULL REFERENCES users(id) ON DELETE CASCADE, created_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP, updated_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP, CONSTRAINT uq_budget_user_category_month UNIQUE(user_id, category, month)
);
CREATE INDEX idx_budgets_user_month ON budgets(user_id, month);
CREATE TABLE transactions (
 id BIGSERIAL PRIMARY KEY, amount NUMERIC(19,2) NOT NULL CHECK (amount > 0), category VARCHAR(80) NOT NULL, description VARCHAR(255), transaction_type VARCHAR(20) NOT NULL, account_id BIGINT NOT NULL REFERENCES accounts(id) ON DELETE CASCADE, user_id BIGINT NOT NULL REFERENCES users(id) ON DELETE CASCADE, occurred_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP, created_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP
);
CREATE INDEX idx_transactions_user_date ON transactions(user_id, occurred_at DESC);
CREATE INDEX idx_transactions_account ON transactions(account_id);
